services:
  - type: web
    name: cricket-api
    env: docker
    region: singapore
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /health
    autoDeploy: true
