services:
  - type: web
    name: cricket-api
    env: node
    buildCommand: npm install
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /health
    autoDeploy: true
