services:
  - type: web
    name: cricket-api
    env: docker
    region: singapore
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: MONGODB_URI
        value: mongodb+srv://vishal_v:Vishal%244866@cluster0.jmbsf.mongodb.net/cricket_api?retryWrites=true&w=majority&appName=Cluster0
    healthCheckPath: /health
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerCommand: node start.js
    port: 3000
